export const PRISMA_CLIENT = "PRISMA_CLIENT";
export const STORAGE_CLIENT = "STORAGE_CLIENT";
export const MANIFEST_URL_EXPIRY_SEC = "MANIFEST_URL_EXPIRY_SEC";
export const MANIFEST_URL_SIGNER = "MANIFEST_URL_SIGNER";
